- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.daws84ss.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  # ignore_errors: true
  # ignore_unreachable: true

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  # ignore_errors: true
  # ignore_unreachable: true

- name: Create /app/db directory
  ansible.builtin.file:
    path: /app/db
    state: directory
  

- name: Copy master-data.js to target
  ansible.builtin.copy:
    src: master-data.js
    dest: /app/db/master-data.js
  
- name: Load products
  ansible.builtin.shell: mongosh --host mongodb.daws84ss.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0


  # ignore_errors: true
  # ignore_unreachable: true

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml

- name: Deployment
  tags: 
  - deployment
  import_role:
    name: common
    tasks_from: deployment